# Generated by Django 2.2.10 on 2020-06-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('finished', models.BooleanField(default=False)),
                ('slug', models.SlugField()),
            ],
            options={
                'unique_together': {('slug', 'name')},
            },
        ),
    ]
