# Generated by Django 2.2.10 on 2020-06-12 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='todo',
            unique_together={('name',)},
        ),
        migrations.RemoveField(
            model_name='todo',
            name='slug',
        ),
    ]
